CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Email NVARCHAR(255) NOT NULL UNIQUE,
    FirstName NVARCHAR(100) NOT NULL, 
    LastName NVARCHAR(100) NOT NULL,  
    PasswordHash NVARCHAR(MAX) NULL,
    AvatarUrl NVARCHAR(1000) NULL,
    Role NVARCHAR(50) NOT NULL DEFAULT 'User', -- 'Admin', 'User'
    
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    IsDeleted BIT NOT NULL DEFAULT 0
);
CREATE INDEX IX_Users_Email ON Users(Email) WHERE IsDeleted = 0;