CREATE TABLE Boards (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Title NVARCHAR(200) NOT NULL,
    Description NVARCHAR(1000) NULL,
    OwnerId UNIQUEIDENTIFIER NOT NULL,
    BackgroundColor NVARCHAR(20) NULL DEFAULT '#0079BF',
    
 
    IsArchived BIT NOT NULL DEFAULT 0,
    ArchivedAt DATETIME2 NULL,
    
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    IsDeleted BIT NOT NULL DEFAULT 0,
    
    CONSTRAINT FK_Boards_Owner FOREIGN KEY (OwnerId) REFERENCES Users(Id)
);
CREATE INDEX IX_Boards_OwnerId ON Boards(OwnerId) WHERE IsDeleted = 0;
