CREATE TABLE BoardMembers (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    BoardId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Role INT NOT NULL DEFAULT 3, 
    JoinedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    
    CONSTRAINT FK_BoardMembers_Board FOREIGN KEY (BoardId) REFERENCES Boards(Id) ON DELETE CASCADE,
    CONSTRAINT FK_BoardMembers_User FOREIGN KEY (UserId) REFERENCES Users(Id),
    CONSTRAINT UQ_BoardMembers_BoardUser UNIQUE (BoardId, UserId)
);