CREATE TABLE TaskLists (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    BoardId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(200) NOT NULL,
    Position INT NOT NULL DEFAULT 0,
    
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    IsDeleted BIT NOT NULL DEFAULT 0,
    
    CONSTRAINT FK_TaskLists_Board FOREIGN KEY (BoardId) REFERENCES Boards(Id) ON DELETE CASCADE
);
