CREATE TABLE Tasks (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ListId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(300) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    AssignedUserId UNIQUEIDENTIFIER NULL,
    Position INT NOT NULL DEFAULT 0,
    DueDate DATETIME2 NULL,
    
    Priority INT NOT NULL DEFAULT 2, -- 2-Medium
    
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    IsDeleted BIT NOT NULL DEFAULT 0,
    
    CONSTRAINT FK_Tasks_List FOREIGN KEY (ListId) REFERENCES TaskLists(Id) ON DELETE CASCADE,
    CONSTRAINT FK_Tasks_AssignedUser FOREIGN KEY (AssignedUserId) REFERENCES Users(Id) ON DELETE SET NULL
);
CREATE INDEX IX_Tasks_ListId ON Tasks(ListId, Position) WHERE IsDeleted = 0;
