CREATE TABLE Labels (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    BoardId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Color NVARCHAR(20) NOT NULL DEFAULT '#61BD4F',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    
    CONSTRAINT FK_Labels_Board FOREIGN KEY (BoardId) REFERENCES Boards(Id) ON DELETE CASCADE
);