CREATE TABLE ChatSessions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    SessionType NVARCHAR(50) NOT NULL DEFAULT 'FAQ', -- 'FAQ', 'Support', 'General'
    StartedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    EndedAt DATETIME2 NULL,
    MessageCount INT NOT NULL DEFAULT 0,
    
    CONSTRAINT FK_ChatSessions_User FOREIGN KEY (UserId) 
        REFERENCES Users(Id) ON DELETE CASCADE
);