CREATE TABLE ChecklistItems (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ChecklistId UNIQUEIDENTIFIER NOT NULL,
    Text NVARCHAR(500) NOT NULL,
    IsChecked BIT NOT NULL DEFAULT 0,
    Position INT NOT NULL DEFAULT 0,
    DueDate DATETIME2 NULL,
    AssignedUserId UNIQUEIDENTIFIER NULL,
    
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    IsDeleted BIT NOT NULL DEFAULT 0,
    
    CONSTRAINT FK_ChecklistItems_Checklist FOREIGN KEY (ChecklistId) 
        REFERENCES Checklists(Id) ON DELETE CASCADE,
    CONSTRAINT FK_ChecklistItems_AssignedUser FOREIGN KEY (AssignedUserId) 
        REFERENCES Users(Id) ON DELETE SET NULL
);